### ISSUE TITLE
Gizmo with Celerity

### ISSUE THREAD

**Issue by leonardoanalista** [icaruswings/gizmo#3]
hey Luke, Is it possible to use Gizmo with Celerity?
I am trying but I got an error in the method "on_page" in the helpers.rb. 

cheers 
Leonardo

**Comment by icaruswings** [comment]
Hey Leo,

I haven't before, but it should not interfere with it.

whats the error your getting?
and what does your step definition code look like?

first thing to try would be not call the on_page_with block variable 'page'. that could be conflicting with something

so

on_page_with :some_mixin do |page|
...code...
end

becomes

on_page_with :some_mixin do |my_page|
..code...
end

maybe something your doing inside your code block needs to access the capybara 'page' object which would be overridden locally in the block?

let me know if that works

**Comment by leonardoanalista** [comment]
This is my env.rb:
$LOAD_PATH.unshift(File.dirname(**FILE**) + '/../../lib')

require 'gizmo'
World(Gizmo::Helpers)

Gizmo.configure do |config|
  config.mixin_dir = File.dirname(**FILE**) + '/features/support/pages'
end

I also have the folders bin and lib in the root of the project. One that comes with the example in https://github.com/icaruswings/gizmo.git

This is the error:
    Then CL_the system shows the help page                      # features/step_definitions/help_steps.rb:7
      undefined local variable or method `response' for #Object:0x998 (NameError)

I renamed "page" to "pagex" in my on_page_with... 
I think now fails in the method:  " def valid? "   

 def valid?
    puts "I can see this! @@@@@ GIZMO!!!! "
    pagex.has_xpath?("/html/body/table/tbody/tr[2]/td/div/div/h4")
  end

Error still similar: undefined local variable or method `page' for #Gizmo::Page:0x19bd0b1 (NameError)

But to get to this point I did some hacky code in the helpers.rb, just to test:
    def on_page &block
      #resp = response
      resp = $br #this is my celerity alias to @browser
      raise NilResponseError, "Doh! response object is nil. This generally means your scenario has not yet visited a page!" if resp.nil?
      yield Page.new(self, resp.html, resp.url)
      #yield Page.new(self, resp.body, current_url)
    end

I don't know if this is causing any side effects...
what do you think is happening? 

thanks Luke

**Comment by icaruswings** [comment]
your missing the response object.. easy fix.. check out this wiki page

https://github.com/icaruswings/gizmo/wiki/Capybara

let me know if that works..
